version: 0.1

phases:
  build:
    commands:
    - chmod +x gradlew
    - ./gradlew buildZip
  post_build:
    commands:
    - aws cloudformation package --s3-bucket com.techcasita.s3.bucket --template-file template.yml --output-template-file output-template.yml
artifacts:
  files:
  - output-template.yml
  discard-paths: yes