AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: P4 PrimeCheck Serverless App
Resources:
  PostFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/distributions/PrimeCICD-1.0.zip
      FunctionName: primecheck-cicd
      Handler: com.techcasita.lambda.Prime
      Runtime: java8
      Timeout: 10
      MemorySize: 512
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /
            Method: post
