AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An example SAM template for Lambda Safe Deployments.

Resources:

  PrimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.techcasita.lambda.Prime
      Runtime: java8
      CodeUri:
        Bucket: com.techcasita.s3.bucket
        Key: build/app.zip
      MemorySize: 1024
      Timeout: 60
      Policies:
      - Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Action:
          - "s3:ListAllMyBuckets"
          Resource: '*'
      DeploymentPreference:
        Type: Linear10PercentEvery1Minute
        Hooks:
          PreTraffic: !Ref preTrafficHook
      Events:
        Api:
          Type: Api
          Properties:
            Path: /pc
            Method: post

  preTrafficHook:
    Type: AWS::Serverless::Function
    Properties:
      Handler: preTrafficHook.handler
      Policies:
      - Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Action:
          - "codedeploy:PutLifecycleEventHookExecutionStatus"
          Resource:
            !Sub 'arn:aws:codedeploy:${AWS::Region}:${AWS::AccountId}:deploymentgroup:${ServerlessDeploymentApplication}/*'
      - Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Action:
          - "lambda:InvokeFunction"
          Resource: !Ref returnS3Buckets.Version
      Runtime: nodejs6.10
      FunctionName: 'CodeDeployHook_preTrafficHook'
      DeploymentPreference:
        Enabled: false
      Timeout: 5
      Environment:
        Variables:
          NewVersion: !Ref returnS3Buckets.Version